spring.application.name=MS1

server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET_KEY}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch registry from Eureka
eureka.client.fetch-registry=true

# Display IP address in Eureka Dashboard (Optional)
eureka.instance.prefer-ip-address=true
