spring.application.name=MS-API-GATEWAY

server.port=8000

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register Gateway with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#################################################
# Route 1 : Addition Service
#################################################

spring.cloud.gateway.routes[0].id=MS1
spring.cloud.gateway.routes[0].uri=lb://MS1
spring.cloud.gateway.routes[0].predicates[0]=Path=/ms1/**

#################################################
# Route 2 : Multiplication Service
#################################################

spring.cloud.gateway.routes[1].id=MS2
spring.cloud.gateway.routes[1].uri=lb://MS2
spring.cloud.gateway.routes[1].predicates[0]=Path=/ms2/**
